---
- name: Install Ubuntu cloud keys package
  apt: name=ubuntu-cloud-keyring

- name: Add Ocata Ubuntu cloud repository
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main' state=present update_cache=yes

- name: install nova-compute package
  apt: name={{ item }}
  with_items:
    - nova-compute
    - sysfsutils

- name: Disable rp filters
  sysctl: name={{ item }} value=0 state=present
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
- name: Install neutron compute packages
  apt: name={{ item }}
  with_items:
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
- name: Copy neutron.conf file
  template: src=neutron.conf dest=/etc/neutron/neutron.conf owner=root group=neutron mode=0640
  notify:
    - restart neutron-linuxbridge-agent
- name: Copy ml2_conf.ini file
  copy: src=ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner=root group=neutron mode=0640
  notify:
    - restart neutron-linuxbridge-agent
- name: Copy linuxbridge_agent.ini file
  copy: src=linuxbridge_agent.ini dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini owner=root group=neutron mode=0640
  notify:
    - restart neutron-linuxbridge-agent


- name: install nova.conf file
  template: src=nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0640
  notify:
    - restart nova-compute

- name: delete Ubuntu Nova package sqlite database
  file: path=/var/lib/nova/nova.sqlite state=absent

