---
- name: Add Zabbix apt repo key
  apt_key: url='https://repo.zabbix.com/zabbix-official-repo.key' state=present
- name: Add Zabbix repository
  apt_repository: repo='deb http://repo.zabbix.com/zabbix/3.4/ubuntu xenial main' state=present update_cache=yes filename=zabbix
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
- name: Add Zabbix repository
  apt_repository: repo='deb http://repo.zabbix.com/zabbix/3.4/ubuntu trusty main' state=present update_cache=yes filename=zabbix
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
- name: Install Zabbix agent
  apt: name=zabbix-agent state=latest
- name: Copy custom parameters configuration
  copy: src=userparameter_megaraid.conf dest=/etc/zabbix/zabbix_agentd.d/
  notify:
    - restart zabbix-agent
- copy: src=userparameter_ntp.conf dest=/etc/zabbix/zabbix_agentd.d/
  notify:
    - restart zabbix-agent
- name: Add user parameters for CEPH
  copy: src=ceph.conf dest=/etc/zabbix/zabbix_agentd.d/
  when: "'ceph' in group_names"
  notify:
    - restart zabbix-agent
- name: Add NVidia user paramenters
  copy: src=userparameter_nvidia.conf dest=/etc/zabbix/zabbix_agentd.d/
  when: "'nvidia_gpus' in group_names"
  notify:
    - restart zabbix-agent
- name: Copy Zabbix agent configuration file
  copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  notify:
    - restart zabbix-agent
- copy: src=userparameter_diskstats.conf dest=/etc/zabbix/zabbix_agentd.d/
  notify:
    - restart zabbix-agent
- copy: src=lld-disks.py dest=/usr/local/bin mode=0755

