---
- name: Install influxdata repository key
  apt_key: state=present url=https://repos.influxdata.com/influxdb.key
- name: Add influxdata repository
  apt_repository: repo='deb http://repos.influxdata.com/ubuntu trusty stable' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
- name: Add influxdata repository
  apt_repository: repo='deb http://repos.influxdata.com/ubuntu xenial stable' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
- apt: name=telegraf state=latest
- apt: name=supervisor state=present
- service: name=telegraf enabled=no state=stopped
- copy: src=supervisord.conf dest=/etc/supervisor/conf.d/telegraf.conf owner=root mode=0644
- template: src=telegraf.conf dest=/etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
- user: name=telegraf groups=docker append=yes
  when: "'docker' in group_names"
  notify:
    - restart telegraf

