---
- name: Install influxdata repository key
  copy: src=repo.key dest=/tmp/repo.key
- apt_key: state=present file=/tmp/repo.key
- name: Add influxdata repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present update_cache=no
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
- name: Add influxdata repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu xenial stable' state=present update_cache=no
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
- apt_repository: repo='deb http://repos.influxdata.com/ubuntu trusty stable' state=absent update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
- apt_repository: repo='deb http://repos.influxdata.com/ubuntu xenial stable' state=absent update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
- copy: src=sdumper dest=/usr/local/bin/sdumper owner=root group=root mode=0755
  notify:
    - restart sdumper
- file: path=/mnt/cephfs/datasets/platform/telegraf/{{ ansible_hostname }} owner=telegraf group=telegraf state=directory
- apt: name=telegraf state=latest
- apt: name=supervisor state=present
- service: name=telegraf enabled=no state=stopped
- template: src=supervisord.conf dest=/etc/supervisor/conf.d/telegraf.conf owner=root mode=0644
  notify:
    - update supervisor
- template: src=telegraf.conf dest=/etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
- user: name=telegraf groups=docker append=yes
  when: "'docker' in group_names"
  notify:
    - restart telegraf

