#!/usr/bin/python
import logging
import sys
import argparse

import novacfg
import novaqueue
#import novapdns # This is for PowerDNS
import dnsupdate # This is for Bind-style ddns
import background

# parse command line arguments
def parseArgs():
   parser = argparse.ArgumentParser(description='openstackdns')
   parser.add_argument('-c', action="store", dest="configfile", required=True)
   parser.add_argument('-d', action="store_true", dest="debug")

   args = parser.parse_args()
   return(args)

def main(argv):

   # parse up the command line arguments
   args = parseArgs()

   # parse the config file
   config = novacfg.novaConfig(args.configfile)

   logger = logging.getLogger('novadns')

   if not args.debug:
      background.createDaemon()
      logLevel = logging.INFO # switch to info if not debugging
      hdlr = logging.FileHandler( config.get('LOG', 'logfile') )
   else:
      logLevel = logging.DEBUG # default to debug
      hdlr = logging.StreamHandler(sys.stderr)

   # first we setup the logger
   formatter = logging.Formatter('%(asctime)s [%(levelname)s] %(message)s')
   hdlr.setFormatter(formatter)
   logger.addHandler(hdlr) 

   logger.setLevel(logLevel)

   logger.info("Starting openstack-dns")

   # make a pdns object to deal with talking to the database
   #dns = novapdns.pdnsDatabase(config)
   dns = dnsupdate.DDNSUpdate(config)

   # make a queue object to watch qpid for nova messages
   try:
      queue = novaqueue.novaQueue(config, dns)
   except:
      logger.exception("Something bad happened")

if __name__ == "__main__":
    main(sys.argv[1:])

