---
- name: ensure sudoers file contains NOPASSWD for sudo users
  lineinfile: dest=/etc/sudoers state=present regexp='^%sudo ALL\=' line='%sudo ALL=(ALL:ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: create the deploy group for ansible
  group: name=deploy state=present

- name: create the deploy user for ansible
  user: name=deploy shell=/bin/bash group=deploy groups=sudo,adm,plugdev,cdrom,dip append=yes

- name: add public key for deploy access
  authorized_key: user=deploy key={{ lookup('file', 'deploy.pub') }}

- name: apt-cache-ng proxy
  copy: src=apt_proxy dest=/etc/apt/apt.conf.d/02proxy 
  when: ansible_hostname != "bf5"

- name: install NTP daemon
  apt: name=ntp

- name: copy NTP config file
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify:
    - restart ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=started enabled=yes

- name: install ceph mount command
  apt: name=ceph-fs-common
- group: name=ceph state=present system=yes

- name: create ceph conf directory
  file: path=/etc/ceph state=directory mode=0770 group=ceph owner=root

- name: copy ceph key
  copy: src=/mnt/cephfs/admin/ceph/client.admin.key dest=/etc/ceph/client.admin.key

- name: add cephfs to fstab and mount it
  mount: name=/mnt/cephfs src=192.168.46.1:/ fstype=ceph opts=name=admin,secretfile=/etc/ceph/client.admin.key,_netdev state=mounted

- name: install an MTA
  apt: name=msmtp
- apt: name=msmtp-mta
- copy: src=msmtprc dest=/etc/msmtprc
- copy: src=msmtprc-aliases dest=/etc/aliases

- name: install megaraid tool
  apt_key: state=present url=https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
- apt_repository: repo='deb http://hwraid.le-vert.net/ubuntu xenial main' state=present update_cache=yes filename=hwraid
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
- apt_repository: repo='deb http://hwraid.le-vert.net/ubuntu trusty main' state=present update_cache=yes filename=hwraid
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
  apt: name=megacli

