---
- name: Install the graylog sidecar collector
  apt:
    deb: https://github.com/Graylog2/collector-sidecar/releases/download/0.1.7/collector-sidecar_0.1.7-1_amd64.deb
    state: present
- name: Copy common configuration
  template:
    src: collector_sidecar.yml
    dest: /etc/graylog/collector-sidecar/collector_sidecar.yml
    owner: root
    group: root
  notify:
    - restart graylog-sidecar
- name: Install service
  command: graylog-collector-sidecar -service install
  args:
    creates: /etc/systemd/system/collector-sidecar.service
- name: enable and start service
  service:
    enabled: true
    state: started
    name: collector-sidecar

