---
- name: update libvirt conf
  copy: src=libvirtd.conf dest=/etc/libvirt/libvirtd.conf
  notify:
    - restart libvirt-bin

- name: update libvirt init conf
  copy: src=libvirtd dest=/etc/default/libvirtd
  notify:
    - restart libvirtd
