---
- hosts: all
  remote_user: venzano
  become: yes
  roles:
    - common
    - rsyslog
    - telegraf
    - zabbix
    - graylog-sidecar
    - webmin
  tasks:
    - name: Clean-up left-over packages
      apt: autoremove=yes

